services:
  deppat:
    image: ghcr.io/commanderredyt/deppat.jetzt:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:5050:3000"

  test:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:5050:3000"
