#!/bin/bash

# check if docker-compose or docker compose
if [ -x "$(command -v docker-compose)" ]; then
  docker-compose -f docker-compose.yml up -d test
else
  docker compose -f docker-compose.yml up -d test
fi
